### ISSUE TITLE
[erreur] message d'erreur en cas de publication de commentaire ou de script

### ISSUE THREAD

**Issue by Lantea-Git** [jvscript/jvscript.io#23]
vito y'a un message d'erreur en cas de publication de commentaire ou de script.
**Alors ça ne bloque pas la mise en ligne ça marche très bien***

Mais au moment de poster un commentaire ou un script : 

on a cette image (même si ça marche => on peut le voir après refresh) : 
![Sans titre 1](https://github.com/user-attachments/assets/8e9d7546-2ed0-447a-945b-e498e555a8ca)

Bizarrement quand on laisse un commentaire **sur son propre script** => ça bug pas 

Mais le message d'erreur s'affiche 90% du temps

J'ai test sur brave, Firefox avec différentes versions de Chromium ça ne semble pas venir coté client ou à cause d'un bloqueur.

**Comment by vitoo** [comment]
Oui c'est un probleme de mail, je regarde ça

**Comment by vitoo** [comment]
Résolu
